//
//  R.swift
//  InspectionTool
//
//  Created by Dan Leonard on 3/1/18.
//
//  This file is autogenerated by ResourceGenerator.swift
//
// `R` represents Resource a common practace used in other development enviroments.


enum R {
    
    /** Checked Out */
    static var checkedOut = {
            NSLocalizedString("checkedOut", comment: "Checked Out")}()

    /** Vehicle Search */
    static var vehicleSearch = {
            NSLocalizedString("vehicleSearch", comment: "Vehicle Search")}()

    /** Please add as much information as possible about every part replaced and repair performed for this vehicle.  */
    static var pleaseAddAsMuchInformationAsPossibleAboutEveryPartReplaced = {
            NSLocalizedString("pleaseAddAsMuchInformationAsPossibleAboutEveryPartReplaced", comment: "Please add as much information as possible about every part replaced and repair performed for this vehicle. ")}()

    /** The seller verifies that the odometer stated above is ACTUAL or NOT ACTUAL and will be represented as such circled mileage type on the title. */
    static var theSellerVerifiesThatTheOdometerStatedAboveIsActualOr = {
            NSLocalizedString("theSellerVerifiesThatTheOdometerStatedAboveIsActualOr", comment: "The seller verifies that the odometer stated above is ACTUAL or NOT ACTUAL and will be represented as such circled mileage type on the title.")}()

    /** Manager */
    static var manager = {
            NSLocalizedString("manager", comment: "Manager")}()

    /** Dealer Consignment Agreement Terms* */
    static var dealerConsignmentAgreementTerms = {
            NSLocalizedString("dealerConsignmentAgreementTerms", comment: "Dealer Consignment Agreement Terms*")}()

    /** Shipment Information */
    static var shipmentInformation = {
            NSLocalizedString("shipmentInformation", comment: "Shipment Information")}()

    /** Start: */
    static var start = {
            NSLocalizedString("start", comment: "Start:")}()

    /** Supplier */
    static var supplier = {
            NSLocalizedString("supplier", comment: "Supplier")}()

    /** Unable to log in */
    static var unableToLogIn = {
            NSLocalizedString("unableToLogIn", comment: "Unable to log in")}()

    /** Displacement */
    static var displacement = {
            NSLocalizedString("displacement", comment: "Displacement")}()

    /** Add Dealer */
    static var addDealer = {
            NSLocalizedString("addDealer", comment: "Add Dealer")}()

    /** You must select a specific Shipping From Area */
    static var youMustSelectASpecificShippingFromArea = {
            NSLocalizedString("youMustSelectASpecificShippingFromArea", comment: "You must select a specific Shipping From Area")}()

    /** Paid */
    static var paid = {
            NSLocalizedString("paid", comment: "Paid")}()

    /** Supplier Inspection PDF */
    static var supplierInspectionPdf = {
            NSLocalizedString("supplierInspectionPdf", comment: "Supplier Inspection PDF")}()

    /** Insurance Classification */
    static var insuranceClassification = {
            NSLocalizedString("insuranceClassification", comment: "Insurance Classification")}()

    /** To Reinspect - PPU */
    static var toReinspectPpu = {
            NSLocalizedString("toReinspectPpu", comment: "To Reinspect - PPU")}()

    /** Request Payment */
    static var requestPayment = {
            NSLocalizedString("requestPayment", comment: "Request Payment")}()

    /** Would you like to mark this shipment as %@? */
    static var wouldYouLikeToMarkThisShipmentAs = {
            NSLocalizedString("wouldYouLikeToMarkThisShipmentAs", comment: "Would you like to mark this shipment as %@?")}()

    /** Purchase price can be updated in vAuto. */
    static var purchasePriceCanBeUpdatedInVauto = {
            NSLocalizedString("purchasePriceCanBeUpdatedInVauto", comment: "Purchase price can be updated in vAuto.")}()

    /** Purchase Price */
    static var purchasePrice = {
            NSLocalizedString("purchasePrice", comment: "Purchase Price")}()

    /** Theft */
    static var theft = {
            NSLocalizedString("theft", comment: "Theft")}()

    /** Reject */
    static var reject = {
            NSLocalizedString("reject", comment: "Reject")}()

    /** Vandalism */
    static var vandalism = {
            NSLocalizedString("vandalism", comment: "Vandalism")}()

    /** Shipment Filters */
    static var shipmentFilters = {
            NSLocalizedString("shipmentFilters", comment: "Shipment Filters")}()

    /** Reinspection */
    static var reinspection = {
            NSLocalizedString("reinspection", comment: "Reinspection")}()

    /** Title Front Image */
    static var titleFrontImage = {
            NSLocalizedString("titleFrontImage", comment: "Title Front Image")}()

    /** COD */
    static var cod = {
            NSLocalizedString("cod", comment: "COD")}()

    /** Manual */
    static var manual = {
            NSLocalizedString("manual", comment: "Manual")}()

    /** Region */
    static var region = {
            NSLocalizedString("region", comment: "Region")}()

    /** Save */
    static var save = {
            NSLocalizedString("save", comment: "Save")}()

    /** New Shipping Company */
    static var newShippingCompany = {
            NSLocalizedString("newShippingCompany", comment: "New Shipping Company")}()

    /** ASN Suppliers Not Available */
    static var asnSuppliersNotAvailable = {
            NSLocalizedString("asnSuppliersNotAvailable", comment: "ASN Suppliers Not Available")}()

    /** New Supplying Location */
    static var newSupplyingLocation = {
            NSLocalizedString("newSupplyingLocation", comment: "New Supplying Location")}()

    /** Inspector */
    static var inspector = {
            NSLocalizedString("inspector", comment: "Inspector")}()

    /** Mileage Classification */
    static var mileageClassification = {
            NSLocalizedString("mileageClassification", comment: "Mileage Classification")}()

    /** Phone Number */
    static var phoneNumber = {
            NSLocalizedString("phoneNumber", comment: "Phone Number")}()

    /** Shipment Vehicles */
    static var shipmentVehicles = {
            NSLocalizedString("shipmentVehicles", comment: "Shipment Vehicles")}()

    /** Search Processes */
    static var searchProcesses = {
            NSLocalizedString("searchProcesses", comment: "Search Processes")}()

    /** The supplier does not have any email addresses. Please add one in the rebuilder tool. */
    static var theSupplierDoesNotHaveAnyEmailAddressesPleaseAddOne = {
            NSLocalizedString("theSupplierDoesNotHaveAnyEmailAddressesPleaseAddOne", comment: "The supplier does not have any email addresses. Please add one in the rebuilder tool.")}()

    /** Seller acknowledges they will warranty the vehicle while the vehicle is located at one of AutoSource’s dealerships and for an additional 6 months or 6,000 miles from AutoSource’s retail date of sale, whichever occurs first. They will cover all major components (engine, transmission, electrical & mechanical systems, fuel systems, heating/AC systems, etc) plus any breakdowns/needed repairs resultant from a sub-standard repair or issues resulting from initial damage. */
    static var sellerAcknowledgesTheyWillWarrantyTheVehicleWhileTheVehicleIs = {
            NSLocalizedString("sellerAcknowledgesTheyWillWarrantyTheVehicleWhileTheVehicleIs", comment: "Seller acknowledges they will warranty the vehicle while the vehicle is located at one of AutoSource’s dealerships and for an additional 6 months or 6,000 miles from AutoSource’s retail date of sale, whichever occurs first. They will cover all major components (engine, transmission, electrical & mechanical systems, fuel systems, heating/AC systems, etc) plus any breakdowns/needed repairs resultant from a sub-standard repair or issues resulting from initial damage.")}()

    /** Other Classification */
    static var otherClassification = {
            NSLocalizedString("otherClassification", comment: "Other Classification")}()

    /** Edit Inspection */
    static var editInspection = {
            NSLocalizedString("editInspection", comment: "Edit Inspection")}()

    /** State */
    static var state = {
            NSLocalizedString("state", comment: "State")}()

    /** Abandoned Deal */
    static var abandonedDeal = {
            NSLocalizedString("abandonedDeal", comment: "Abandoned Deal")}()

    /** BOS Awaiting */
    static var bosAwaiting = {
            NSLocalizedString("bosAwaiting", comment: "BOS Awaiting")}()

    /** Clean */
    static var clean = {
            NSLocalizedString("clean", comment: "Clean")}()

    /** No. of Units */
    static var noOfUnits = {
            NSLocalizedString("noOfUnits", comment: "No. of Units")}()

    /** Quick Pay */
    static var quickPay = {
            NSLocalizedString("quickPay", comment: "Quick Pay")}()

    /** Shipping From */
    static var shippingFrom = {
            NSLocalizedString("shippingFrom", comment: "Shipping From")}()

    /** Add Note */
    static var addNote = {
            NSLocalizedString("addNote", comment: "Add Note")}()

    /** Shipped To */
    static var shippedTo = {
            NSLocalizedString("shippedTo", comment: "Shipped To")}()

    /** Vehicle Title */
    static var vehicleTitle = {
            NSLocalizedString("vehicleTitle", comment: "Vehicle Title")}()

    /** No Price */
    static var noPrice = {
            NSLocalizedString("noPrice", comment: "No Price")}()

    /** City/State/Zip */
    static var citystatezip = {
            NSLocalizedString("citystatezip", comment: "City/State/Zip")}()

    /** Date */
    static var date = {
            NSLocalizedString("date", comment: "Date")}()

    /** Net 15 */
    static var net15 = {
            NSLocalizedString("net15", comment: "Net 15")}()

    /** Driver Phone Number */
    static var driverPhoneNumber = {
            NSLocalizedString("driverPhoneNumber", comment: "Driver Phone Number")}()

    /** Note */
    static var note = {
            NSLocalizedString("note", comment: "Note")}()

    /** Shipping Cost */
    static var shippingCost = {
            NSLocalizedString("shippingCost", comment: "Shipping Cost")}()

    /** New Vehicle Information */
    static var newVehicleInformation = {
            NSLocalizedString("newVehicleInformation", comment: "New Vehicle Information")}()

    /** Select Area */
    static var selectArea = {
            NSLocalizedString("selectArea", comment: "Select Area")}()

    /** All Areas */
    static var allAreas = {
            NSLocalizedString("allAreas", comment: "All Areas")}()

    /** Options */
    static var options = {
            NSLocalizedString("options", comment: "Options")}()

    /** Select Region */
    static var selectRegion = {
            NSLocalizedString("selectRegion", comment: "Select Region")}()

    /** Zip Code */
    static var zipCode = {
            NSLocalizedString("zipCode", comment: "Zip Code")}()

    /** Cancel and abandon your changes? */
    static var cancelAndAbandonYourChanges = {
            NSLocalizedString("cancelAndAbandonYourChanges", comment: "Cancel and abandon your changes?")}()

    /** Mileage */
    static var mileage = {
            NSLocalizedString("mileage", comment: "Mileage")}()

    /** Dealer Address */
    static var dealerAddress = {
            NSLocalizedString("dealerAddress", comment: "Dealer Address")}()

    /** Both */
    static var both = {
            NSLocalizedString("both", comment: "Both")}()

    /** BOS */
    static var bos = {
            NSLocalizedString("bos", comment: "BOS")}()

    /** Changing the area will remove all vehicles from this shipment */
    static var changingTheAreaWillRemoveAllVehiclesFromThisShipment = {
            NSLocalizedString("changingTheAreaWillRemoveAllVehiclesFromThisShipment", comment: "Changing the area will remove all vehicles from this shipment")}()

    /** Request */
    static var request = {
            NSLocalizedString("request", comment: "Request")}()

    /** Search Shipments */
    static var searchShipments = {
            NSLocalizedString("searchShipments", comment: "Search Shipments")}()

    /** Bill of Sale In Person */
    static var billOfSaleInPerson = {
            NSLocalizedString("billOfSaleInPerson", comment: "Bill of Sale In Person")}()

    /** Full Inspection PDF */
    static var fullInspectionPdf = {
            NSLocalizedString("fullInspectionPdf", comment: "Full Inspection PDF")}()

    /** Burn */
    static var burn = {
            NSLocalizedString("burn", comment: "Burn")}()

    /** Universal Search */
    static var universalSearch = {
            NSLocalizedString("universalSearch", comment: "Universal Search")}()

    /** Searching */
    static var searching = {
            NSLocalizedString("searching", comment: "Searching")}()

    /** Shipment Details */
    static var shipmentDetails = {
            NSLocalizedString("shipmentDetails", comment: "Shipment Details")}()

    /** Parts Replaced/Repairs* */
    static var partsReplacedrepairs = {
            NSLocalizedString("partsReplacedrepairs", comment: "Parts Replaced/Repairs*")}()

    /** Automatic */
    static var automatic = {
            NSLocalizedString("automatic", comment: "Automatic")}()

    /** Inspection PDF */
    static var inspectionPdf = {
            NSLocalizedString("inspectionPdf", comment: "Inspection PDF")}()

    /** Bill of Sale */
    static var billOfSale = {
            NSLocalizedString("billOfSale", comment: "Bill of Sale")}()

    /** Edit Shipment Details */
    static var editShipmentDetails = {
            NSLocalizedString("editShipmentDetails", comment: "Edit Shipment Details")}()

    /** Date Created */
    static var dateCreated = {
            NSLocalizedString("dateCreated", comment: "Date Created")}()

    /** Shipping To */
    static var shippingTo = {
            NSLocalizedString("shippingTo", comment: "Shipping To")}()

    /** Component does not apply */
    static var componentDoesNotApply = {
            NSLocalizedString("componentDoesNotApply", comment: "Component does not apply")}()

    /** Report */
    static var report = {
            NSLocalizedString("report", comment: "Report")}()

    /** To Reinspect @ ASM Shop */
    static var toReinspectAsmShop = {
            NSLocalizedString("toReinspectAsmShop", comment: "To Reinspect @ ASM Shop")}()

    /** Advanced Filtering */
    static var advancedFiltering = {
            NSLocalizedString("advancedFiltering", comment: "Advanced Filtering")}()

    /** Collect Signatures */
    static var collectSignatures = {
            NSLocalizedString("collectSignatures", comment: "Collect Signatures")}()

    /** In Transit */
    static var inTransit = {
            NSLocalizedString("inTransit", comment: "In Transit")}()

    /** Water Recovery */
    static var waterRecovery = {
            NSLocalizedString("waterRecovery", comment: "Water Recovery")}()

    /** Shipping Notes */
    static var shippingNotes = {
            NSLocalizedString("shippingNotes", comment: "Shipping Notes")}()

    /** BOS History */
    static var bosHistory = {
            NSLocalizedString("bosHistory", comment: "BOS History")}()

    /** Back */
    static var back = {
            NSLocalizedString("back", comment: "Back")}()

    /** Vehicle Not Approved */
    static var vehicleNotApproved = {
            NSLocalizedString("vehicleNotApproved", comment: "Vehicle Not Approved")}()

    /** New Retail Location */
    static var newRetailLocation = {
            NSLocalizedString("newRetailLocation", comment: "New Retail Location")}()

    /** Create */
    static var create = {
            NSLocalizedString("create", comment: "Create")}()

    /** Initial */
    static var initial = {
            NSLocalizedString("initial", comment: "Initial")}()

    /** Inspection Summary */
    static var inspectionSummary = {
            NSLocalizedString("inspectionSummary", comment: "Inspection Summary")}()

    /** Loading Vehicles... */
    static var loadingVehicles = {
            NSLocalizedString("loadingVehicles", comment: "Loading Vehicles...")}()

    /** Mark Arrived */
    static var markArrived = {
            NSLocalizedString("markArrived", comment: "Mark Arrived")}()

    /** Are you sure you want to reject this inspection? */
    static var areYouSureYouWantToRejectThisInspection = {
            NSLocalizedString("areYouSureYouWantToRejectThisInspection", comment: "Are you sure you want to reject this inspection?")}()

    /** Arrived */
    static var arrived = {
            NSLocalizedString("arrived", comment: "Arrived")}()

    /** Bill of Lading Image 2 */
    static var billOfLadingImage2 = {
            NSLocalizedString("billOfLadingImage2", comment: "Bill of Lading Image 2")}()

    /** Inspected */
    static var inspected = {
            NSLocalizedString("inspected", comment: "Inspected")}()

    /** Update */
    static var update = {
            NSLocalizedString("update", comment: "Update")}()

    /** The odometer you entered is more than 1000 miles different than the original. Is this correct? */
    static var theOdometerYouEnteredIsMoreThan1000MilesDifferentThan = {
            NSLocalizedString("theOdometerYouEnteredIsMoreThan1000MilesDifferentThan", comment: "The odometer you entered is more than 1000 miles different than the original. Is this correct?")}()

    /** Bad Credentials */
    static var badCredentials = {
            NSLocalizedString("badCredentials", comment: "Bad Credentials")}()

    /** VIN (Last 8) */
    static var vinLast8 = {
            NSLocalizedString("vinLast8", comment: "VIN (Last 8)")}()

    /** Clear Filters */
    static var clearFilters = {
            NSLocalizedString("clearFilters", comment: "Clear Filters")}()

    /** Reject Repair */
    static var rejectRepair = {
            NSLocalizedString("rejectRepair", comment: "Reject Repair")}()

    /** Vehicle Information */
    static var vehicleInformation = {
            NSLocalizedString("vehicleInformation", comment: "Vehicle Information")}()

    /** Edit Shipment Vehicles */
    static var editShipmentVehicles = {
            NSLocalizedString("editShipmentVehicles", comment: "Edit Shipment Vehicles")}()

    /** Seller verifies vehicle has been repaired to the manufacturer’s specifications and all airbags, seatbelts, & SRS systems equipped in this vehicle are original, or have been replaced and are in 100% working order. */
    static var sellerVerifiesVehicleHasBeenRepairedToTheManufacturersSpecificationsAnd = {
            NSLocalizedString("sellerVerifiesVehicleHasBeenRepairedToTheManufacturersSpecificationsAnd", comment: "Seller verifies vehicle has been repaired to the manufacturer’s specifications and all airbags, seatbelts, & SRS systems equipped in this vehicle are original, or have been replaced and are in 100% working order.")}()

    /** Needs Attention */
    static var needsAttention = {
            NSLocalizedString("needsAttention", comment: "Needs Attention")}()

    /** Additional Image %lu */
    static var additionalImageLu = {
            NSLocalizedString("additionalImageLu", comment: "Additional Image %lu")}()

    /** No results */
    static var noResults = {
            NSLocalizedString("noResults", comment: "No results")}()

    /** Component is acceptable */
    static var componentIsAcceptable = {
            NSLocalizedString("componentIsAcceptable", comment: "Component is acceptable")}()

    /** Seller */
    static var seller = {
            NSLocalizedString("seller", comment: "Seller")}()

    /** Transmission Type */
    static var transmissionType = {
            NSLocalizedString("transmissionType", comment: "Transmission Type")}()

    /** BOS Completed */
    static var bosCompleted = {
            NSLocalizedString("bosCompleted", comment: "BOS Completed")}()

    /** View Bill of Lading */
    static var viewBillOfLading = {
            NSLocalizedString("viewBillOfLading", comment: "View Bill of Lading")}()

    /** Seller acknowledges that they will not get paid until the vehicle is sold & AutoSource has been fully funded. */
    static var sellerAcknowledgesThatTheyWillNotGetPaidUntilTheVehicle = {
            NSLocalizedString("sellerAcknowledgesThatTheyWillNotGetPaidUntilTheVehicle", comment: "Seller acknowledges that they will not get paid until the vehicle is sold & AutoSource has been fully funded.")}()

    /** Choose the preferred email address to receive the PDF */
    static var chooseThePreferredEmailAddressToReceiveThePdf = {
            NSLocalizedString("chooseThePreferredEmailAddressToReceiveThePdf", comment: "Choose the preferred email address to receive the PDF")}()

    /** Bill of Lading */
    static var billOfLading = {
            NSLocalizedString("billOfLading", comment: "Bill of Lading")}()

    /** VIN */
    static var vin = {
            NSLocalizedString("vin", comment: "VIN")}()

    /** Engine Size */
    static var engineSize = {
            NSLocalizedString("engineSize", comment: "Engine Size")}()

    /** Inspection Tool */
    static var inspectionTool = {
            NSLocalizedString("inspectionTool", comment: "Inspection Tool")}()

    /** Legend */
    static var legend = {
            NSLocalizedString("legend", comment: "Legend")}()

    /** Shipment Status */
    static var shipmentStatus = {
            NSLocalizedString("shipmentStatus", comment: "Shipment Status")}()

    /** Are you sure? */
    static var areYouSure = {
            NSLocalizedString("areYouSure", comment: "Are you sure?")}()

    /** Component needs further review */
    static var componentNeedsFurtherReview = {
            NSLocalizedString("componentNeedsFurtherReview", comment: "Component needs further review")}()

    /** Name */
    static var name = {
            NSLocalizedString("name", comment: "Name")}()

    /** Reset */
    static var reset = {
            NSLocalizedString("reset", comment: "Reset")}()

    /** Inspection Overview */
    static var inspectionOverview = {
            NSLocalizedString("inspectionOverview", comment: "Inspection Overview")}()

    /** All Regions */
    static var allRegions = {
            NSLocalizedString("allRegions", comment: "All Regions")}()

    /** Edit Vehicles */
    static var editVehicles = {
            NSLocalizedString("editVehicles", comment: "Edit Vehicles")}()

    /** Salvage */
    static var salvage = {
            NSLocalizedString("salvage", comment: "Salvage")}()

    /** Edit */
    static var edit = {
            NSLocalizedString("edit", comment: "Edit")}()

    /** Resend for Signatures */
    static var resendForSignatures = {
            NSLocalizedString("resendForSignatures", comment: "Resend for Signatures")}()

    /** Submit */
    static var submit = {
            NSLocalizedString("submit", comment: "Submit")}()

    /** Appraised Value */
    static var appraisedValue = {
            NSLocalizedString("appraisedValue", comment: "Appraised Value")}()

    /** Not Actual Mileage */
    static var notActualMileage = {
            NSLocalizedString("notActualMileage", comment: "Not Actual Mileage")}()

    /** Please Wait */
    static var pleaseWait = {
            NSLocalizedString("pleaseWait", comment: "Please Wait")}()

    /** Title PDF */
    static var titlePdf = {
            NSLocalizedString("titlePdf", comment: "Title PDF")}()

    /** Address Line 1 */
    static var addressLine1 = {
            NSLocalizedString("addressLine1", comment: "Address Line 1")}()

    /** Edit Bill of Sale */
    static var editBillOfSale = {
            NSLocalizedString("editBillOfSale", comment: "Edit Bill of Sale")}()

    /** Model */
    static var model = {
            NSLocalizedString("model", comment: "Model")}()

    /** P/NADA */
    static var pnada = {
            NSLocalizedString("pnada", comment: "P/NADA")}()

    /** Shipping Company */
    static var shippingCompany = {
            NSLocalizedString("shippingCompany", comment: "Shipping Company")}()

    /** Apply Filters */
    static var applyFilters = {
            NSLocalizedString("applyFilters", comment: "Apply Filters")}()

    /** Saved Photos */
    static var savedPhotos = {
            NSLocalizedString("savedPhotos", comment: "Saved Photos")}()

    /** The vehicle information has not yet been imported. Enter some basic information about this vehicle. */
    static var theVehicleInformationHasNotYetBeenImportedEnterSomeBasic = {
            NSLocalizedString("theVehicleInformationHasNotYetBeenImportedEnterSomeBasic", comment: "The vehicle information has not yet been imported. Enter some basic information about this vehicle.")}()

    /** Bill of Sale PDF */
    static var billOfSalePdf = {
            NSLocalizedString("billOfSalePdf", comment: "Bill of Sale PDF")}()

    /** This user is not currently setup to use this app. */
    static var thisUserIsNotCurrentlySetupToUseThisApp = {
            NSLocalizedString("thisUserIsNotCurrentlySetupToUseThisApp", comment: "This user is not currently setup to use this app.")}()

    /** Payment Initiated */
    static var paymentInitiated = {
            NSLocalizedString("paymentInitiated", comment: "Payment Initiated")}()

    /** Comment */
    static var comment = {
            NSLocalizedString("comment", comment: "Comment")}()

    /** Total Units */
    static var totalUnits = {
            NSLocalizedString("totalUnits", comment: "Total Units")}()

    /** Retail Location */
    static var retailLocation = {
            NSLocalizedString("retailLocation", comment: "Retail Location")}()

    /** Edit Title */
    static var editTitle = {
            NSLocalizedString("editTitle", comment: "Edit Title")}()

    /** Seller acknowledges that if vehicle does not sell after 120 days on AutoSource retail lots the vehicle will be shipped back at the Seller’s expense. */
    static var sellerAcknowledgesThatIfVehicleDoesNotSellAfter120Days = {
            NSLocalizedString("sellerAcknowledgesThatIfVehicleDoesNotSellAfter120Days", comment: "Seller acknowledges that if vehicle does not sell after 120 days on AutoSource retail lots the vehicle will be shipped back at the Seller’s expense.")}()

    /** N/A */
    static var na = {
            NSLocalizedString("na", comment: "N/A")}()

    /** Saving... */
    static var saving = {
            NSLocalizedString("saving", comment: "Saving...")}()

    /** Cancel */
    static var cancel = {
            NSLocalizedString("cancel", comment: "Cancel")}()

    /** Shipping */
    static var shipping = {
            NSLocalizedString("shipping", comment: "Shipping")}()

    /** Unauthorized */
    static var unauthorized = {
            NSLocalizedString("unauthorized", comment: "Unauthorized")}()

    /** Other */
    static var other = {
            NSLocalizedString("other", comment: "Other")}()

    /** Email */
    static var email = {
            NSLocalizedString("email", comment: "Email")}()

    /** Vehicle Pending Approval */
    static var vehiclePendingApproval = {
            NSLocalizedString("vehiclePendingApproval", comment: "Vehicle Pending Approval")}()

    /** BOS Not Approved */
    static var bosNotApproved = {
            NSLocalizedString("bosNotApproved", comment: "BOS Not Approved")}()

    /** End: */
    static var end = {
            NSLocalizedString("end", comment: "End:")}()

    /** Supplier Telephone */
    static var supplierTelephone = {
            NSLocalizedString("supplierTelephone", comment: "Supplier Telephone")}()

    /** NADA Clean Trade */
    static var nadaCleanTrade = {
            NSLocalizedString("nadaCleanTrade", comment: "NADA Clean Trade")}()

    /** Editing is allowed for mileage and supplier. Other vehicle information should be set in vAuto. */
    static var editingIsAllowedForMileageAndSupplierOtherVehicleInformationShould = {
            NSLocalizedString("editingIsAllowedForMileageAndSupplierOtherVehicleInformationShould", comment: "Editing is allowed for mileage and supplier. Other vehicle information should be set in vAuto.")}()

    /** Supplier Name */
    static var supplierName = {
            NSLocalizedString("supplierName", comment: "Supplier Name")}()

    /** Fail */
    static var fail = {
            NSLocalizedString("fail", comment: "Fail")}()

    /** Confirm */
    static var confirm = {
            NSLocalizedString("confirm", comment: "Confirm")}()

    /** Vehicle Import */
    static var vehicleImport = {
            NSLocalizedString("vehicleImport", comment: "Vehicle Import")}()

    /** Error */
    static var error = {
            NSLocalizedString("error", comment: "Error")}()

    /** Add Supplier */
    static var addSupplier = {
            NSLocalizedString("addSupplier", comment: "Add Supplier")}()

    /** Title */
    static var title = {
            NSLocalizedString("title", comment: "Title")}()

    /** Reason */
    static var reason = {
            NSLocalizedString("reason", comment: "Reason")}()

    /** Will the seller initial and sign the bill of sale in person? */
    static var willTheSellerInitialAndSignTheBillOfSaleIn = {
            NSLocalizedString("willTheSellerInitialAndSignTheBillOfSaleIn", comment: "Will the seller initial and sign the bill of sale in person?")}()

    /** Odometer Disclosure */
    static var odometerDisclosure = {
            NSLocalizedString("odometerDisclosure", comment: "Odometer Disclosure")}()

    /** This vehicle is missing information. Please go to vAuto and update this vehicle's information. */
    static var thisVehicleIsMissingInformationPleaseGoToVautoAndUpdate = {
            NSLocalizedString("thisVehicleIsMissingInformationPleaseGoToVautoAndUpdate", comment: "This vehicle is missing information. Please go to vAuto and update this vehicle's information.")}()

    /** Shipped Date */
    static var shippedDate = {
            NSLocalizedString("shippedDate", comment: "Shipped Date")}()

    /** Username */
    static var username = {
            NSLocalizedString("username", comment: "Username")}()

    /** BOS Approved */
    static var bosApproved = {
            NSLocalizedString("bosApproved", comment: "BOS Approved")}()

    /** Payment Request Form */
    static var paymentRequestForm = {
            NSLocalizedString("paymentRequestForm", comment: "Payment Request Form")}()

    /** All Statuses */
    static var allStatuses = {
            NSLocalizedString("allStatuses", comment: "All Statuses")}()

    /** Reject Inspection? */
    static var rejectInspection = {
            NSLocalizedString("rejectInspection", comment: "Reject Inspection?")}()

    /** No Results Found */
    static var noResultsFound = {
            NSLocalizedString("noResultsFound", comment: "No Results Found")}()

    /** Completed */
    static var completed = {
            NSLocalizedString("completed", comment: "Completed")}()

    /** Trim */
    static var trim = {
            NSLocalizedString("trim", comment: "Trim")}()

    /** Price Not Recognized as Currency */
    static var priceNotRecognizedAsCurrency = {
            NSLocalizedString("priceNotRecognizedAsCurrency", comment: "Price Not Recognized as Currency")}()

    /** No */
    static var no = {
            NSLocalizedString("no", comment: "No")}()

    /** Driver Phone */
    static var driverPhone = {
            NSLocalizedString("driverPhone", comment: "Driver Phone")}()

    /** OK */
    static var ok = {
            NSLocalizedString("ok", comment: "OK")}()

    /** Please select a Shipping From Area */
    static var pleaseSelectAShippingFromArea = {
            NSLocalizedString("pleaseSelectAShippingFromArea", comment: "Please select a Shipping From Area")}()

    /** Edit Vehicle Information */
    static var editVehicleInformation = {
            NSLocalizedString("editVehicleInformation", comment: "Edit Vehicle Information")}()

    /** Rejected */
    static var rejected = {
            NSLocalizedString("rejected", comment: "Rejected")}()

    /** Seller acknowledges they will warranty any/all paint work done to the above vehicle while the vehicle is located at one of AutoSource’s dealerships and for an additional 12 months or 12,000 miles from AutoSource’s retail date of sale, whichever occurs first. */
    static var sellerAcknowledgesTheyWillWarrantyAnyallPaintWorkDoneToThe = {
            NSLocalizedString("sellerAcknowledgesTheyWillWarrantyAnyallPaintWorkDoneToThe", comment: "Seller acknowledges they will warranty any/all paint work done to the above vehicle while the vehicle is located at one of AutoSource’s dealerships and for an additional 12 months or 12,000 miles from AutoSource’s retail date of sale, whichever occurs first.")}()

    /** Phone Number must be valid */
    static var phoneNumberMustBeValid = {
            NSLocalizedString("phoneNumberMustBeValid", comment: "Phone Number must be valid")}()

    /** Clear Note */
    static var clearNote = {
            NSLocalizedString("clearNote", comment: "Clear Note")}()

    /** Retry */
    static var retry = {
            NSLocalizedString("retry", comment: "Retry")}()

    /** Clear Photo */
    static var clearPhoto = {
            NSLocalizedString("clearPhoto", comment: "Clear Photo")}()

    /** No Vehicles Selected */
    static var noVehiclesSelected = {
            NSLocalizedString("noVehiclesSelected", comment: "No Vehicles Selected")}()

    /** Parts Replaced/Repaired */
    static var partsReplacedrepaired = {
            NSLocalizedString("partsReplacedrepaired", comment: "Parts Replaced/Repaired")}()

    /** Full VIN or Last 8 of VIN */
    static var fullVinOrLast8OfVin = {
            NSLocalizedString("fullVinOrLast8OfVin", comment: "Full VIN or Last 8 of VIN")}()

    /** Shipped On */
    static var shippedOn = {
            NSLocalizedString("shippedOn", comment: "Shipped On")}()

    /** City */
    static var city = {
            NSLocalizedString("city", comment: "City")}()

    /** Supplier Information: %1$@ */
    static var supplierInformation1 = {
            NSLocalizedString("supplierInformation1", comment: "Supplier Information: %1$@")}()

    /** Authenticating */
    static var authenticating = {
            NSLocalizedString("authenticating", comment: "Authenticating")}()

    /** Password */
    static var password = {
            NSLocalizedString("password", comment: "Password")}()

    /** BOS Awaiting Signature */
    static var bosAwaitingSignature = {
            NSLocalizedString("bosAwaitingSignature", comment: "BOS Awaiting Signature")}()

    /** Inspector Name */
    static var inspectorName = {
            NSLocalizedString("inspectorName", comment: "Inspector Name")}()

    /** Pass */
    static var pass = {
            NSLocalizedString("pass", comment: "Pass")}()

    /** First Inspection */
    static var firstInspection = {
            NSLocalizedString("firstInspection", comment: "First Inspection")}()

    /** Login */
    static var login = {
            NSLocalizedString("login", comment: "Login")}()

    /** Network Error */
    static var networkError = {
            NSLocalizedString("networkError", comment: "Network Error")}()

    /** Pending */
    static var pending = {
            NSLocalizedString("pending", comment: "Pending")}()

    /** Select Status */
    static var selectStatus = {
            NSLocalizedString("selectStatus", comment: "Select Status")}()

    /** Vehicle Approved */
    static var vehicleApproved = {
            NSLocalizedString("vehicleApproved", comment: "Vehicle Approved")}()

    /** Reinspection Count */
    static var reinspectionCount = {
            NSLocalizedString("reinspectionCount", comment: "Reinspection Count")}()

    /** Status */
    static var status = {
            NSLocalizedString("status", comment: "Status")}()

    /** Arrived Date */
    static var arrivedDate = {
            NSLocalizedString("arrivedDate", comment: "Arrived Date")}()

    /** Unreject */
    static var unreject = {
            NSLocalizedString("unreject", comment: "Unreject")}()

    /** Choose or add a dealer to system unless this is a one-off sale. */
    static var chooseOrAddADealerToSystemUnlessThisIsA = {
            NSLocalizedString("chooseOrAddADealerToSystemUnlessThisIsA", comment: "Choose or add a dealer to system unless this is a one-off sale.")}()

    /** Shipped From */
    static var shippedFrom = {
            NSLocalizedString("shippedFrom", comment: "Shipped From")}()

    /** Consignment */
    static var consignment = {
            NSLocalizedString("consignment", comment: "Consignment")}()

    /** Supplier Number */
    static var supplierNumber = {
            NSLocalizedString("supplierNumber", comment: "Supplier Number")}()

    /** Last known location */
    static var lastKnownLocation = {
            NSLocalizedString("lastKnownLocation", comment: "Last known location")}()

    /** Create Bill of Sale & Payment Request */
    static var createBillOfSalePaymentRequest = {
            NSLocalizedString("createBillOfSalePaymentRequest", comment: "Create Bill of Sale & Payment Request")}()

    /** Clear search and filter */
    static var clearSearchAndFilter = {
            NSLocalizedString("clearSearchAndFilter", comment: "Clear search and filter")}()

    /** Vehicle Filters */
    static var vehicleFilters = {
            NSLocalizedString("vehicleFilters", comment: "Vehicle Filters")}()

    /** Payment */
    static var payment = {
            NSLocalizedString("payment", comment: "Payment")}()

    /** Phone Number must be no more than 16 digits */
    static var phoneNumberMustBeNoMoreThan16Digits = {
            NSLocalizedString("phoneNumberMustBeNoMoreThan16Digits", comment: "Phone Number must be no more than 16 digits")}()

    /** Settings */
    static var settings = {
            NSLocalizedString("settings", comment: "Settings")}()

    /** Payment Method */
    static var paymentMethod = {
            NSLocalizedString("paymentMethod", comment: "Payment Method")}()

    /** There was an error updating the title images. */
    static var thereWasAnErrorUpdatingTheTitleImages = {
            NSLocalizedString("thereWasAnErrorUpdatingTheTitleImages", comment: "There was an error updating the title images.")}()

    /** Notes */
    static var notes = {
            NSLocalizedString("notes", comment: "Notes")}()

    /** Review BOS */
    static var reviewBos = {
            NSLocalizedString("reviewBos", comment: "Review BOS")}()

    /** BOS Pending Approval */
    static var bosPendingApproval = {
            NSLocalizedString("bosPendingApproval", comment: "BOS Pending Approval")}()

    /** Specify other classification */
    static var specifyOtherClassification = {
            NSLocalizedString("specifyOtherClassification", comment: "Specify other classification")}()

    /** Seller Signature* */
    static var sellerSignature = {
            NSLocalizedString("sellerSignature", comment: "Seller Signature*")}()

    /** There can only be 10 vehicles per shipment */
    static var thereCanOnlyBe10VehiclesPerShipment = {
            NSLocalizedString("thereCanOnlyBe10VehiclesPerShipment", comment: "There can only be 10 vehicles per shipment")}()

    /** Seller Type */
    static var sellerType = {
            NSLocalizedString("sellerType", comment: "Seller Type")}()

    /** Warning */
    static var warning = {
            NSLocalizedString("warning", comment: "Warning")}()

    /** Photo Library */
    static var photoLibrary = {
            NSLocalizedString("photoLibrary", comment: "Photo Library")}()

    /** Drivetrain */
    static var drivetrain = {
            NSLocalizedString("drivetrain", comment: "Drivetrain")}()

    /** Dealer Purchase Agreement Terms */
    static var dealerPurchaseAgreementTerms = {
            NSLocalizedString("dealerPurchaseAgreementTerms", comment: "Dealer Purchase Agreement Terms")}()

    /** Phone */
    static var phone = {
            NSLocalizedString("phone", comment: "Phone")}()

    /** Driver */
    static var driver = {
            NSLocalizedString("driver", comment: "Driver")}()

    /** Odometer */
    static var odometer = {
            NSLocalizedString("odometer", comment: "Odometer")}()

    /** Resend Bill of Sale for Signatures */
    static var resendBillOfSaleForSignatures = {
            NSLocalizedString("resendBillOfSaleForSignatures", comment: "Resend Bill of Sale for Signatures")}()

    /** Supplier Email */
    static var supplierEmail = {
            NSLocalizedString("supplierEmail", comment: "Supplier Email")}()

    /** Body Style */
    static var bodyStyle = {
            NSLocalizedString("bodyStyle", comment: "Body Style")}()

    /** Driver Name */
    static var driverName = {
            NSLocalizedString("driverName", comment: "Driver Name")}()

    /** Vehicle checked out by
%1$@
%2$@
%3$@

%1$@ would lose any unsaved work.

Proceed if you are sure you should. */
    static var vehicleCheckedOutBy1231WouldLoseAnyUnsavedWorkproceedIfYou = {
            NSLocalizedString("vehicleCheckedOutBy1231WouldLoseAnyUnsavedWorkproceedIfYou", comment: "Vehicle checked out by\n%1$@\n%2$@\n%3$@\n\n%1$@ would lose any unsaved work.\n\nProceed if you are sure you should.")}()

    /** Search */
    static var search = {
            NSLocalizedString("search", comment: "Search")}()

    /** Create Bill of Sale */
    static var createBillOfSale = {
            NSLocalizedString("createBillOfSale", comment: "Create Bill of Sale")}()

    /** Color */
    static var color = {
            NSLocalizedString("color", comment: "Color")}()

    /** Last Modified */
    static var lastModified = {
            NSLocalizedString("lastModified", comment: "Last Modified")}()

    /** Zip Code must be between 5 and 10 digits */
    static var zipCodeMustBeBetween5And10Digits = {
            NSLocalizedString("zipCodeMustBeBetween5And10Digits", comment: "Zip Code must be between 5 and 10 digits")}()

    /** Front */
    static var front = {
            NSLocalizedString("front", comment: "Front")}()

    /** Title History */
    static var titleHistory = {
            NSLocalizedString("titleHistory", comment: "Title History")}()

    /** Area */
    static var area = {
            NSLocalizedString("area", comment: "Area")}()

    /** Year */
    static var year = {
            NSLocalizedString("year", comment: "Year")}()

    /** Search for a vehicle using the Full VIN or Last 8 of VIN. If the vehicle is not already in the system you will be able to enter the details manually. */
    static var searchForAVehicleUsingTheFullVinOrLast8 = {
            NSLocalizedString("searchForAVehicleUsingTheFullVinOrLast8", comment: "Search for a vehicle using the Full VIN or Last 8 of VIN. If the vehicle is not already in the system you will be able to enter the details manually.")}()

    /** Bill of Lading Image 1 */
    static var billOfLadingImage1 = {
            NSLocalizedString("billOfLadingImage1", comment: "Bill of Lading Image 1")}()

    /** Title Back Image */
    static var titleBackImage = {
            NSLocalizedString("titleBackImage", comment: "Title Back Image")}()

    /** Take photo */
    static var takePhoto = {
            NSLocalizedString("takePhoto", comment: "Take photo")}()

    /** Buyer Signature* */
    static var buyerSignature = {
            NSLocalizedString("buyerSignature", comment: "Buyer Signature*")}()

    /** Close */
    static var close = {
            NSLocalizedString("close", comment: "Close")}()

    /** Select an Account */
    static var selectAnAccount = {
            NSLocalizedString("selectAnAccount", comment: "Select an Account")}()

    /** Vehicle checked out by
%1$@
%2$@
%3$@

Please contact %1$@ before continuing or try again in a moment. */
    static var vehicleCheckedOutBy123PleaseContact1BeforeContinuingOrTryAgain = {
            NSLocalizedString("vehicleCheckedOutBy123PleaseContact1BeforeContinuingOrTryAgain", comment: "Vehicle checked out by\n%1$@\n%2$@\n%3$@\n\nPlease contact %1$@ before continuing or try again in a moment.")}()

    /** Trim/Series */
    static var trimseries = {
            NSLocalizedString("trimseries", comment: "Trim/Series")}()

    /** Your changes will be lost */
    static var yourChangesWillBeLost = {
            NSLocalizedString("yourChangesWillBeLost", comment: "Your changes will be lost")}()

    /** Cylinders */
    static var cylinders = {
            NSLocalizedString("cylinders", comment: "Cylinders")}()

    /** Shipment No - %@ */
    static var shipmentNo = {
            NSLocalizedString("shipmentNo", comment: "Shipment No - %@")}()

    /** Create Shipment */
    static var createShipment = {
            NSLocalizedString("createShipment", comment: "Create Shipment")}()

    /** Supplying Location */
    static var supplyingLocation = {
            NSLocalizedString("supplyingLocation", comment: "Supplying Location")}()

    /** Component is unacceptable */
    static var componentIsUnacceptable = {
            NSLocalizedString("componentIsUnacceptable", comment: "Component is unacceptable")}()

    /** Make */
    static var make = {
            NSLocalizedString("make", comment: "Make")}()

    /** Hail Damage */
    static var hailDamage = {
            NSLocalizedString("hailDamage", comment: "Hail Damage")}()

    /** Component has been acceptably repaired */
    static var componentHasBeenAcceptablyRepaired = {
            NSLocalizedString("componentHasBeenAcceptablyRepaired", comment: "Component has been acceptably repaired")}()

    /** Fixed */
    static var fixed = {
            NSLocalizedString("fixed", comment: "Fixed")}()

    /** Send to Supplier */
    static var sendToSupplier = {
            NSLocalizedString("sendToSupplier", comment: "Send to Supplier")}()

    /** Actual Mileage */
    static var actualMileage = {
            NSLocalizedString("actualMileage", comment: "Actual Mileage")}()

    /** Shipments */
    static var shipments = {
            NSLocalizedString("shipments", comment: "Shipments")}()

    /** No inspections matched the specified criteria */
    static var noInspectionsMatchedTheSpecifiedCriteria = {
            NSLocalizedString("noInspectionsMatchedTheSpecifiedCriteria", comment: "No inspections matched the specified criteria")}()

    /** Address */
    static var address = {
            NSLocalizedString("address", comment: "Address")}()

    /** Seller acknowledges they will be responsible for all shipping costs incurred if the vehicle is to be sent back for any reason, and will pay AutoSource before they pick up the vehicle from AutoSource Office. */
    static var sellerAcknowledgesTheyWillBeResponsibleForAllShippingCostsIncurred = {
            NSLocalizedString("sellerAcknowledgesTheyWillBeResponsibleForAllShippingCostsIncurred", comment: "Seller acknowledges they will be responsible for all shipping costs incurred if the vehicle is to be sent back for any reason, and will pay AutoSource before they pick up the vehicle from AutoSource Office.")}()

    /** Install the ASN Suppliers tool in order to add Supplier information. */
    static var installTheAsnSuppliersToolInOrderToAddSupplierInformation = {
            NSLocalizedString("installTheAsnSuppliersToolInOrderToAddSupplierInformation", comment: "Install the ASN Suppliers tool in order to add Supplier information.")}()

    /** Submit BOS/PMT */
    static var submitBospmt = {
            NSLocalizedString("submitBospmt", comment: "Submit BOS/PMT")}()

    /** Collision */
    static var collision = {
            NSLocalizedString("collision", comment: "Collision")}()

    /** Inspection Passed */
    static var inspectionPassed = {
            NSLocalizedString("inspectionPassed", comment: "Inspection Passed")}()

    /** Bank Account */
    static var bankAccount = {
            NSLocalizedString("bankAccount", comment: "Bank Account")}()

    /** To Reinspect @ Supplier */
    static var toReinspectSupplier = {
            NSLocalizedString("toReinspectSupplier", comment: "To Reinspect @ Supplier")}()

    /** Retake Images */
    static var retakeImages = {
            NSLocalizedString("retakeImages", comment: "Retake Images")}()

    /** Select Vehicle */
    static var selectVehicle = {
            NSLocalizedString("selectVehicle", comment: "Select Vehicle")}()

    /** Title Classification */
    static var titleClassification = {
            NSLocalizedString("titleClassification", comment: "Title Classification")}()

    /** Seller will need to be available via phone (phone number above) during AutoSource business hours Mon-Sat 10-7pm for any/all retail customer negotiations. If Seller does not respond via text or call, AutoSource can lower their cost up to $500 without their permission to consummate any deal. */
    static var sellerWillNeedToBeAvailableViaPhonePhoneNumberAbove = {
            NSLocalizedString("sellerWillNeedToBeAvailableViaPhonePhoneNumberAbove", comment: "Seller will need to be available via phone (phone number above) during AutoSource business hours Mon-Sat 10-7pm for any/all retail customer negotiations. If Seller does not respond via text or call, AutoSource can lower their cost up to $500 without their permission to consummate any deal.")}()

    /** Address Line 2 */
    static var addressLine2 = {
            NSLocalizedString("addressLine2", comment: "Address Line 2")}()

    /** No Inspector */
    static var noInspector = {
            NSLocalizedString("noInspector", comment: "No Inspector")}()

    /** Logout */
    static var logout = {
            NSLocalizedString("logout", comment: "Logout")}()

    /** * denotes preferred account */
    static var denotesPreferredAccount = {
            NSLocalizedString("denotesPreferredAccount", comment: "* denotes preferred account")}()

    /** Mark in Transit */
    static var markInTransit = {
            NSLocalizedString("markInTransit", comment: "Mark in Transit")}()

    /** Loading... */
    static var loading = {
            NSLocalizedString("loading", comment: "Loading...")}()

    /** Rejection Reason */
    static var rejectionReason = {
            NSLocalizedString("rejectionReason", comment: "Rejection Reason")}()

    /** Full Purchase */
    static var fullPurchase = {
            NSLocalizedString("fullPurchase", comment: "Full Purchase")}()

    /** Search Everywhere */
    static var searchEverywhere = {
            NSLocalizedString("searchEverywhere", comment: "Search Everywhere")}()

    /** Check Out */
    static var checkOut = {
            NSLocalizedString("checkOut", comment: "Check Out")}()

    /** Preferred */
    static var preferred = {
            NSLocalizedString("preferred", comment: "Preferred")}()

    /** Payment Requested */
    static var paymentRequested = {
            NSLocalizedString("paymentRequested", comment: "Payment Requested")}()

    /** Dealer */
    static var dealer = {
            NSLocalizedString("dealer", comment: "Dealer")}()

    /** Yes */
    static var yes = {
            NSLocalizedString("yes", comment: "Yes")}()

}
