//
//  r.swift
//  InspectionTool
//
//  Created by Dan Leonard on 3/1/18.
//
//  This file is autogenerated by ResourceGenerator.swift
//
// `r` represents Resource a common practace used in other development enviroments.


struct r {


    static func checkedOut(_ comment: String = "Checked Out") -> String {
        return NSLocalizedString("checkedOut", comment: comment)
    }

    static func vehicleSearch(_ comment: String = "Vehicle Search") -> String {
        return NSLocalizedString("vehicleSearch", comment: comment)
    }

    static func pleaseAddAsMuchInformationAsPossibleAboutEveryPartReplaced(_ comment: String = "Please add as much information as possible about every part replaced and repair performed for this vehicle. ") -> String {
        return NSLocalizedString("pleaseAddAsMuchInformationAsPossibleAboutEveryPartReplaced", comment: comment)
    }

    static func theSellerVerifiesThatTheOdometerStatedAboveIsActualOr(_ comment: String = "The seller verifies that the odometer stated above is ACTUAL or NOT ACTUAL and will be represented as such circled mileage type on the title.") -> String {
        return NSLocalizedString("theSellerVerifiesThatTheOdometerStatedAboveIsActualOr", comment: comment)
    }

    static func manager(_ comment: String = "Manager") -> String {
        return NSLocalizedString("manager", comment: comment)
    }

    static func dealerConsignmentAgreementTerms(_ comment: String = "Dealer Consignment Agreement Terms*") -> String {
        return NSLocalizedString("dealerConsignmentAgreementTerms", comment: comment)
    }

    static func shipmentInformation(_ comment: String = "Shipment Information") -> String {
        return NSLocalizedString("shipmentInformation", comment: comment)
    }

    static func start(_ comment: String = "Start:") -> String {
        return NSLocalizedString("start", comment: comment)
    }

    static func supplier(_ comment: String = "Supplier") -> String {
        return NSLocalizedString("supplier", comment: comment)
    }

    static func unableToLogIn(_ comment: String = "Unable to log in") -> String {
        return NSLocalizedString("unableToLogIn", comment: comment)
    }

    static func displacement(_ comment: String = "Displacement") -> String {
        return NSLocalizedString("displacement", comment: comment)
    }

    static func addDealer(_ comment: String = "Add Dealer") -> String {
        return NSLocalizedString("addDealer", comment: comment)
    }

    static func youMustSelectASpecificShippingFromArea(_ comment: String = "You must select a specific Shipping From Area") -> String {
        return NSLocalizedString("youMustSelectASpecificShippingFromArea", comment: comment)
    }

    static func paid(_ comment: String = "Paid") -> String {
        return NSLocalizedString("paid", comment: comment)
    }

    static func supplierInspectionPdf(_ comment: String = "Supplier Inspection PDF") -> String {
        return NSLocalizedString("supplierInspectionPdf", comment: comment)
    }

    static func insuranceClassification(_ comment: String = "Insurance Classification") -> String {
        return NSLocalizedString("insuranceClassification", comment: comment)
    }

    static func toReinspectPpu(_ comment: String = "To Reinspect - PPU") -> String {
        return NSLocalizedString("toReinspectPpu", comment: comment)
    }

    static func requestPayment(_ comment: String = "Request Payment") -> String {
        return NSLocalizedString("requestPayment", comment: comment)
    }

    static func wouldYouLikeToMarkThisShipmentAs(_ comment: String = "Would you like to mark this shipment as %@?") -> String {
        return NSLocalizedString("wouldYouLikeToMarkThisShipmentAs", comment: comment)
    }

    static func purchasePriceCanBeUpdatedInVauto(_ comment: String = "Purchase price can be updated in vAuto.") -> String {
        return NSLocalizedString("purchasePriceCanBeUpdatedInVauto", comment: comment)
    }

    static func purchasePrice(_ comment: String = "Purchase Price") -> String {
        return NSLocalizedString("purchasePrice", comment: comment)
    }

    static func theft(_ comment: String = "Theft") -> String {
        return NSLocalizedString("theft", comment: comment)
    }

    static func reject(_ comment: String = "Reject") -> String {
        return NSLocalizedString("reject", comment: comment)
    }

    static func vandalism(_ comment: String = "Vandalism") -> String {
        return NSLocalizedString("vandalism", comment: comment)
    }

    static func shipmentFilters(_ comment: String = "Shipment Filters") -> String {
        return NSLocalizedString("shipmentFilters", comment: comment)
    }

    static func reinspection(_ comment: String = "Reinspection") -> String {
        return NSLocalizedString("reinspection", comment: comment)
    }

    static func titleFrontImage(_ comment: String = "Title Front Image") -> String {
        return NSLocalizedString("titleFrontImage", comment: comment)
    }

    static func cod(_ comment: String = "COD") -> String {
        return NSLocalizedString("cod", comment: comment)
    }

    static func manual(_ comment: String = "Manual") -> String {
        return NSLocalizedString("manual", comment: comment)
    }

    static func region(_ comment: String = "Region") -> String {
        return NSLocalizedString("region", comment: comment)
    }

    static func save(_ comment: String = "Save") -> String {
        return NSLocalizedString("save", comment: comment)
    }

    static func newShippingCompany(_ comment: String = "New Shipping Company") -> String {
        return NSLocalizedString("newShippingCompany", comment: comment)
    }

    static func asnSuppliersNotAvailable(_ comment: String = "ASN Suppliers Not Available") -> String {
        return NSLocalizedString("asnSuppliersNotAvailable", comment: comment)
    }

    static func newSupplyingLocation(_ comment: String = "New Supplying Location") -> String {
        return NSLocalizedString("newSupplyingLocation", comment: comment)
    }

    static func inspector(_ comment: String = "Inspector") -> String {
        return NSLocalizedString("inspector", comment: comment)
    }

    static func mileageClassification(_ comment: String = "Mileage Classification") -> String {
        return NSLocalizedString("mileageClassification", comment: comment)
    }

    static func phoneNumber(_ comment: String = "Phone Number") -> String {
        return NSLocalizedString("phoneNumber", comment: comment)
    }

    static func shipmentVehicles(_ comment: String = "Shipment Vehicles") -> String {
        return NSLocalizedString("shipmentVehicles", comment: comment)
    }

    static func searchProcesses(_ comment: String = "Search Processes") -> String {
        return NSLocalizedString("searchProcesses", comment: comment)
    }

    static func theSupplierDoesNotHaveAnyEmailAddressesPleaseAddOne(_ comment: String = "The supplier does not have any email addresses. Please add one in the rebuilder tool.") -> String {
        return NSLocalizedString("theSupplierDoesNotHaveAnyEmailAddressesPleaseAddOne", comment: comment)
    }

    static func sellerAcknowledgesTheyWillWarrantyTheVehicleWhileTheVehicleIs(_ comment: String = "Seller acknowledges they will warranty the vehicle while the vehicle is located at one of AutoSource’s dealerships and for an additional 6 months or 6,000 miles from AutoSource’s retail date of sale, whichever occurs first. They will cover all major components (engine, transmission, electrical & mechanical systems, fuel systems, heating/AC systems, etc) plus any breakdowns/needed repairs resultant from a sub-standard repair or issues resulting from initial damage.") -> String {
        return NSLocalizedString("sellerAcknowledgesTheyWillWarrantyTheVehicleWhileTheVehicleIs", comment: comment)
    }

    static func otherClassification(_ comment: String = "Other Classification") -> String {
        return NSLocalizedString("otherClassification", comment: comment)
    }

    static func editInspection(_ comment: String = "Edit Inspection") -> String {
        return NSLocalizedString("editInspection", comment: comment)
    }

    static func state(_ comment: String = "State") -> String {
        return NSLocalizedString("state", comment: comment)
    }

    static func abandonedDeal(_ comment: String = "Abandoned Deal") -> String {
        return NSLocalizedString("abandonedDeal", comment: comment)
    }

    static func bosAwaiting(_ comment: String = "BOS Awaiting") -> String {
        return NSLocalizedString("bosAwaiting", comment: comment)
    }

    static func clean(_ comment: String = "Clean") -> String {
        return NSLocalizedString("clean", comment: comment)
    }

    static func noOfUnits(_ comment: String = "No. of Units") -> String {
        return NSLocalizedString("noOfUnits", comment: comment)
    }

    static func quickPay(_ comment: String = "Quick Pay") -> String {
        return NSLocalizedString("quickPay", comment: comment)
    }

    static func shippingFrom(_ comment: String = "Shipping From") -> String {
        return NSLocalizedString("shippingFrom", comment: comment)
    }

    static func addNote(_ comment: String = "Add Note") -> String {
        return NSLocalizedString("addNote", comment: comment)
    }

    static func shippedTo(_ comment: String = "Shipped To") -> String {
        return NSLocalizedString("shippedTo", comment: comment)
    }

    static func vehicleTitle(_ comment: String = "Vehicle Title") -> String {
        return NSLocalizedString("vehicleTitle", comment: comment)
    }

    static func noPrice(_ comment: String = "No Price") -> String {
        return NSLocalizedString("noPrice", comment: comment)
    }

    static func citystatezip(_ comment: String = "City/State/Zip") -> String {
        return NSLocalizedString("citystatezip", comment: comment)
    }

    static func date(_ comment: String = "Date") -> String {
        return NSLocalizedString("date", comment: comment)
    }

    static func net15(_ comment: String = "Net 15") -> String {
        return NSLocalizedString("net15", comment: comment)
    }

    static func driverPhoneNumber(_ comment: String = "Driver Phone Number") -> String {
        return NSLocalizedString("driverPhoneNumber", comment: comment)
    }

    static func note(_ comment: String = "Note") -> String {
        return NSLocalizedString("note", comment: comment)
    }

    static func shippingCost(_ comment: String = "Shipping Cost") -> String {
        return NSLocalizedString("shippingCost", comment: comment)
    }

    static func newVehicleInformation(_ comment: String = "New Vehicle Information") -> String {
        return NSLocalizedString("newVehicleInformation", comment: comment)
    }

    static func selectArea(_ comment: String = "Select Area") -> String {
        return NSLocalizedString("selectArea", comment: comment)
    }

    static func allAreas(_ comment: String = "All Areas") -> String {
        return NSLocalizedString("allAreas", comment: comment)
    }

    static func options(_ comment: String = "Options") -> String {
        return NSLocalizedString("options", comment: comment)
    }

    static func selectRegion(_ comment: String = "Select Region") -> String {
        return NSLocalizedString("selectRegion", comment: comment)
    }

    static func zipCode(_ comment: String = "Zip Code") -> String {
        return NSLocalizedString("zipCode", comment: comment)
    }

    static func cancelAndAbandonYourChanges(_ comment: String = "Cancel and abandon your changes?") -> String {
        return NSLocalizedString("cancelAndAbandonYourChanges", comment: comment)
    }

    static func mileage(_ comment: String = "Mileage") -> String {
        return NSLocalizedString("mileage", comment: comment)
    }

    static func dealerAddress(_ comment: String = "Dealer Address") -> String {
        return NSLocalizedString("dealerAddress", comment: comment)
    }

    static func both(_ comment: String = "Both") -> String {
        return NSLocalizedString("both", comment: comment)
    }

    static func bos(_ comment: String = "BOS") -> String {
        return NSLocalizedString("bos", comment: comment)
    }

    static func changingTheAreaWillRemoveAllVehiclesFromThisShipment(_ comment: String = "Changing the area will remove all vehicles from this shipment") -> String {
        return NSLocalizedString("changingTheAreaWillRemoveAllVehiclesFromThisShipment", comment: comment)
    }

    static func request(_ comment: String = "Request") -> String {
        return NSLocalizedString("request", comment: comment)
    }

    static func searchShipments(_ comment: String = "Search Shipments") -> String {
        return NSLocalizedString("searchShipments", comment: comment)
    }

    static func billOfSaleInPerson(_ comment: String = "Bill of Sale In Person") -> String {
        return NSLocalizedString("billOfSaleInPerson", comment: comment)
    }

    static func fullInspectionPdf(_ comment: String = "Full Inspection PDF") -> String {
        return NSLocalizedString("fullInspectionPdf", comment: comment)
    }

    static func burn(_ comment: String = "Burn") -> String {
        return NSLocalizedString("burn", comment: comment)
    }

    static func universalSearch(_ comment: String = "Universal Search") -> String {
        return NSLocalizedString("universalSearch", comment: comment)
    }

    static func searching(_ comment: String = "Searching") -> String {
        return NSLocalizedString("searching", comment: comment)
    }

    static func shipmentDetails(_ comment: String = "Shipment Details") -> String {
        return NSLocalizedString("shipmentDetails", comment: comment)
    }

    static func partsReplacedrepairs(_ comment: String = "Parts Replaced/Repairs*") -> String {
        return NSLocalizedString("partsReplacedrepairs", comment: comment)
    }

    static func inspectionPdf(_ comment: String = "Inspection PDF") -> String {
        return NSLocalizedString("inspectionPdf", comment: comment)
    }

    static func automatic(_ comment: String = "Automatic") -> String {
        return NSLocalizedString("automatic", comment: comment)
    }

    static func billOfSale(_ comment: String = "Bill of Sale") -> String {
        return NSLocalizedString("billOfSale", comment: comment)
    }

    static func editShipmentDetails(_ comment: String = "Edit Shipment Details") -> String {
        return NSLocalizedString("editShipmentDetails", comment: comment)
    }

    static func dateCreated(_ comment: String = "Date Created") -> String {
        return NSLocalizedString("dateCreated", comment: comment)
    }

    static func shippingTo(_ comment: String = "Shipping To") -> String {
        return NSLocalizedString("shippingTo", comment: comment)
    }

    static func componentDoesNotApply(_ comment: String = "Component does not apply") -> String {
        return NSLocalizedString("componentDoesNotApply", comment: comment)
    }

    static func report(_ comment: String = "Report") -> String {
        return NSLocalizedString("report", comment: comment)
    }

    static func toReinspectAsmShop(_ comment: String = "To Reinspect @ ASM Shop") -> String {
        return NSLocalizedString("toReinspectAsmShop", comment: comment)
    }

    static func advancedFiltering(_ comment: String = "Advanced Filtering") -> String {
        return NSLocalizedString("advancedFiltering", comment: comment)
    }

    static func collectSignatures(_ comment: String = "Collect Signatures") -> String {
        return NSLocalizedString("collectSignatures", comment: comment)
    }

    static func inTransit(_ comment: String = "In Transit") -> String {
        return NSLocalizedString("inTransit", comment: comment)
    }

    static func waterRecovery(_ comment: String = "Water Recovery") -> String {
        return NSLocalizedString("waterRecovery", comment: comment)
    }

    static func shippingNotes(_ comment: String = "Shipping Notes") -> String {
        return NSLocalizedString("shippingNotes", comment: comment)
    }

    static func bosHistory(_ comment: String = "BOS History") -> String {
        return NSLocalizedString("bosHistory", comment: comment)
    }

    static func back(_ comment: String = "Back") -> String {
        return NSLocalizedString("back", comment: comment)
    }

    static func vehicleNotApproved(_ comment: String = "Vehicle Not Approved") -> String {
        return NSLocalizedString("vehicleNotApproved", comment: comment)
    }

    static func newRetailLocation(_ comment: String = "New Retail Location") -> String {
        return NSLocalizedString("newRetailLocation", comment: comment)
    }

    static func create(_ comment: String = "Create") -> String {
        return NSLocalizedString("create", comment: comment)
    }

    static func initial(_ comment: String = "Initial") -> String {
        return NSLocalizedString("initial", comment: comment)
    }

    static func inspectionSummary(_ comment: String = "Inspection Summary") -> String {
        return NSLocalizedString("inspectionSummary", comment: comment)
    }

    static func loadingVehicles(_ comment: String = "Loading Vehicles...") -> String {
        return NSLocalizedString("loadingVehicles", comment: comment)
    }

    static func markArrived(_ comment: String = "Mark Arrived") -> String {
        return NSLocalizedString("markArrived", comment: comment)
    }

    static func areYouSureYouWantToRejectThisInspection(_ comment: String = "Are you sure you want to reject this inspection?") -> String {
        return NSLocalizedString("areYouSureYouWantToRejectThisInspection", comment: comment)
    }

    static func arrived(_ comment: String = "Arrived") -> String {
        return NSLocalizedString("arrived", comment: comment)
    }

    static func billOfLadingImage2(_ comment: String = "Bill of Lading Image 2") -> String {
        return NSLocalizedString("billOfLadingImage2", comment: comment)
    }

    static func inspected(_ comment: String = "Inspected") -> String {
        return NSLocalizedString("inspected", comment: comment)
    }

    static func update(_ comment: String = "Update") -> String {
        return NSLocalizedString("update", comment: comment)
    }

    static func theOdometerYouEnteredIsMoreThan1000MilesDifferentThan(_ comment: String = "The odometer you entered is more than 1000 miles different than the original. Is this correct?") -> String {
        return NSLocalizedString("theOdometerYouEnteredIsMoreThan1000MilesDifferentThan", comment: comment)
    }

    static func badCredentials(_ comment: String = "Bad Credentials") -> String {
        return NSLocalizedString("badCredentials", comment: comment)
    }

    static func vinLast8(_ comment: String = "VIN (Last 8)") -> String {
        return NSLocalizedString("vinLast8", comment: comment)
    }

    static func clearFilters(_ comment: String = "Clear Filters") -> String {
        return NSLocalizedString("clearFilters", comment: comment)
    }

    static func rejectRepair(_ comment: String = "Reject Repair") -> String {
        return NSLocalizedString("rejectRepair", comment: comment)
    }

    static func vehicleInformation(_ comment: String = "Vehicle Information") -> String {
        return NSLocalizedString("vehicleInformation", comment: comment)
    }

    static func editShipmentVehicles(_ comment: String = "Edit Shipment Vehicles") -> String {
        return NSLocalizedString("editShipmentVehicles", comment: comment)
    }

    static func sellerVerifiesVehicleHasBeenRepairedToTheManufacturersSpecificationsAnd(_ comment: String = "Seller verifies vehicle has been repaired to the manufacturer’s specifications and all airbags, seatbelts, & SRS systems equipped in this vehicle are original, or have been replaced and are in 100% working order.") -> String {
        return NSLocalizedString("sellerVerifiesVehicleHasBeenRepairedToTheManufacturersSpecificationsAnd", comment: comment)
    }

    static func needsAttention(_ comment: String = "Needs Attention") -> String {
        return NSLocalizedString("needsAttention", comment: comment)
    }

    static func additionalImageLu(_ comment: String = "Additional Image %lu") -> String {
        return NSLocalizedString("additionalImageLu", comment: comment)
    }

    static func noResults(_ comment: String = "No results") -> String {
        return NSLocalizedString("noResults", comment: comment)
    }

    static func componentIsAcceptable(_ comment: String = "Component is acceptable") -> String {
        return NSLocalizedString("componentIsAcceptable", comment: comment)
    }

    static func seller(_ comment: String = "Seller") -> String {
        return NSLocalizedString("seller", comment: comment)
    }

    static func transmissionType(_ comment: String = "Transmission Type") -> String {
        return NSLocalizedString("transmissionType", comment: comment)
    }

    static func bosCompleted(_ comment: String = "BOS Completed") -> String {
        return NSLocalizedString("bosCompleted", comment: comment)
    }

    static func viewBillOfLading(_ comment: String = "View Bill of Lading") -> String {
        return NSLocalizedString("viewBillOfLading", comment: comment)
    }

    static func sellerAcknowledgesThatTheyWillNotGetPaidUntilTheVehicle(_ comment: String = "Seller acknowledges that they will not get paid until the vehicle is sold & AutoSource has been fully funded.") -> String {
        return NSLocalizedString("sellerAcknowledgesThatTheyWillNotGetPaidUntilTheVehicle", comment: comment)
    }

    static func chooseThePreferredEmailAddressToReceiveThePdf(_ comment: String = "Choose the preferred email address to receive the PDF") -> String {
        return NSLocalizedString("chooseThePreferredEmailAddressToReceiveThePdf", comment: comment)
    }

    static func billOfLading(_ comment: String = "Bill of Lading") -> String {
        return NSLocalizedString("billOfLading", comment: comment)
    }

    static func vin(_ comment: String = "VIN") -> String {
        return NSLocalizedString("vin", comment: comment)
    }

    static func engineSize(_ comment: String = "Engine Size") -> String {
        return NSLocalizedString("engineSize", comment: comment)
    }

    static func inspectionTool(_ comment: String = "Inspection Tool") -> String {
        return NSLocalizedString("inspectionTool", comment: comment)
    }

    static func legend(_ comment: String = "Legend") -> String {
        return NSLocalizedString("legend", comment: comment)
    }

    static func shipmentStatus(_ comment: String = "Shipment Status") -> String {
        return NSLocalizedString("shipmentStatus", comment: comment)
    }

    static func areYouSure(_ comment: String = "Are you sure?") -> String {
        return NSLocalizedString("areYouSure", comment: comment)
    }

    static func componentNeedsFurtherReview(_ comment: String = "Component needs further review") -> String {
        return NSLocalizedString("componentNeedsFurtherReview", comment: comment)
    }

    static func name(_ comment: String = "Name") -> String {
        return NSLocalizedString("name", comment: comment)
    }

    static func reset(_ comment: String = "Reset") -> String {
        return NSLocalizedString("reset", comment: comment)
    }

    static func inspectionOverview(_ comment: String = "Inspection Overview") -> String {
        return NSLocalizedString("inspectionOverview", comment: comment)
    }

    static func allRegions(_ comment: String = "All Regions") -> String {
        return NSLocalizedString("allRegions", comment: comment)
    }

    static func editVehicles(_ comment: String = "Edit Vehicles") -> String {
        return NSLocalizedString("editVehicles", comment: comment)
    }

    static func salvage(_ comment: String = "Salvage") -> String {
        return NSLocalizedString("salvage", comment: comment)
    }

    static func edit(_ comment: String = "Edit") -> String {
        return NSLocalizedString("edit", comment: comment)
    }

    static func resendForSignatures(_ comment: String = "Resend for Signatures") -> String {
        return NSLocalizedString("resendForSignatures", comment: comment)
    }

    static func submit(_ comment: String = "Submit") -> String {
        return NSLocalizedString("submit", comment: comment)
    }

    static func appraisedValue(_ comment: String = "Appraised Value") -> String {
        return NSLocalizedString("appraisedValue", comment: comment)
    }

    static func notActualMileage(_ comment: String = "Not Actual Mileage") -> String {
        return NSLocalizedString("notActualMileage", comment: comment)
    }

    static func pleaseWait(_ comment: String = "Please Wait") -> String {
        return NSLocalizedString("pleaseWait", comment: comment)
    }

    static func titlePdf(_ comment: String = "Title PDF") -> String {
        return NSLocalizedString("titlePdf", comment: comment)
    }

    static func addressLine1(_ comment: String = "Address Line 1") -> String {
        return NSLocalizedString("addressLine1", comment: comment)
    }

    static func editBillOfSale(_ comment: String = "Edit Bill of Sale") -> String {
        return NSLocalizedString("editBillOfSale", comment: comment)
    }

    static func model(_ comment: String = "Model") -> String {
        return NSLocalizedString("model", comment: comment)
    }

    static func pnada(_ comment: String = "P/NADA") -> String {
        return NSLocalizedString("pnada", comment: comment)
    }

    static func shippingCompany(_ comment: String = "Shipping Company") -> String {
        return NSLocalizedString("shippingCompany", comment: comment)
    }

    static func applyFilters(_ comment: String = "Apply Filters") -> String {
        return NSLocalizedString("applyFilters", comment: comment)
    }

    static func savedPhotos(_ comment: String = "Saved Photos") -> String {
        return NSLocalizedString("savedPhotos", comment: comment)
    }

    static func theVehicleInformationHasNotYetBeenImportedEnterSomeBasic(_ comment: String = "The vehicle information has not yet been imported. Enter some basic information about this vehicle.") -> String {
        return NSLocalizedString("theVehicleInformationHasNotYetBeenImportedEnterSomeBasic", comment: comment)
    }

    static func billOfSalePdf(_ comment: String = "Bill of Sale PDF") -> String {
        return NSLocalizedString("billOfSalePdf", comment: comment)
    }

    static func thisUserIsNotCurrentlySetupToUseThisApp(_ comment: String = "This user is not currently setup to use this app.") -> String {
        return NSLocalizedString("thisUserIsNotCurrentlySetupToUseThisApp", comment: comment)
    }

    static func paymentInitiated(_ comment: String = "Payment Initiated") -> String {
        return NSLocalizedString("paymentInitiated", comment: comment)
    }

    static func comment(_ comment: String = "Comment") -> String {
        return NSLocalizedString("comment", comment: comment)
    }

    static func totalUnits(_ comment: String = "Total Units") -> String {
        return NSLocalizedString("totalUnits", comment: comment)
    }

    static func retailLocation(_ comment: String = "Retail Location") -> String {
        return NSLocalizedString("retailLocation", comment: comment)
    }

    static func editTitle(_ comment: String = "Edit Title") -> String {
        return NSLocalizedString("editTitle", comment: comment)
    }

    static func sellerAcknowledgesThatIfVehicleDoesNotSellAfter120Days(_ comment: String = "Seller acknowledges that if vehicle does not sell after 120 days on AutoSource retail lots the vehicle will be shipped back at the Seller’s expense.") -> String {
        return NSLocalizedString("sellerAcknowledgesThatIfVehicleDoesNotSellAfter120Days", comment: comment)
    }

    static func na(_ comment: String = "N/A") -> String {
        return NSLocalizedString("na", comment: comment)
    }

    static func saving(_ comment: String = "Saving...") -> String {
        return NSLocalizedString("saving", comment: comment)
    }

    static func cancel(_ comment: String = "Cancel") -> String {
        return NSLocalizedString("cancel", comment: comment)
    }

    static func shipping(_ comment: String = "Shipping") -> String {
        return NSLocalizedString("shipping", comment: comment)
    }

    static func unauthorized(_ comment: String = "Unauthorized") -> String {
        return NSLocalizedString("unauthorized", comment: comment)
    }

    static func other(_ comment: String = "Other") -> String {
        return NSLocalizedString("other", comment: comment)
    }

    static func email(_ comment: String = "Email") -> String {
        return NSLocalizedString("email", comment: comment)
    }

    static func vehiclePendingApproval(_ comment: String = "Vehicle Pending Approval") -> String {
        return NSLocalizedString("vehiclePendingApproval", comment: comment)
    }

    static func bosNotApproved(_ comment: String = "BOS Not Approved") -> String {
        return NSLocalizedString("bosNotApproved", comment: comment)
    }

    static func end(_ comment: String = "End:") -> String {
        return NSLocalizedString("end", comment: comment)
    }

    static func supplierTelephone(_ comment: String = "Supplier Telephone") -> String {
        return NSLocalizedString("supplierTelephone", comment: comment)
    }

    static func nadaCleanTrade(_ comment: String = "NADA Clean Trade") -> String {
        return NSLocalizedString("nadaCleanTrade", comment: comment)
    }

    static func editingIsAllowedForMileageAndSupplierOtherVehicleInformationShould(_ comment: String = "Editing is allowed for mileage and supplier. Other vehicle information should be set in vAuto.") -> String {
        return NSLocalizedString("editingIsAllowedForMileageAndSupplierOtherVehicleInformationShould", comment: comment)
    }

    static func supplierName(_ comment: String = "Supplier Name") -> String {
        return NSLocalizedString("supplierName", comment: comment)
    }

    static func fail(_ comment: String = "Fail") -> String {
        return NSLocalizedString("fail", comment: comment)
    }

    static func confirm(_ comment: String = "Confirm") -> String {
        return NSLocalizedString("confirm", comment: comment)
    }

    static func vehicleImport(_ comment: String = "Vehicle Import") -> String {
        return NSLocalizedString("vehicleImport", comment: comment)
    }

    static func error(_ comment: String = "Error") -> String {
        return NSLocalizedString("error", comment: comment)
    }

    static func addSupplier(_ comment: String = "Add Supplier") -> String {
        return NSLocalizedString("addSupplier", comment: comment)
    }

    static func title(_ comment: String = "Title") -> String {
        return NSLocalizedString("title", comment: comment)
    }

    static func reason(_ comment: String = "Reason") -> String {
        return NSLocalizedString("reason", comment: comment)
    }

    static func willTheSellerInitialAndSignTheBillOfSaleIn(_ comment: String = "Will the seller initial and sign the bill of sale in person?") -> String {
        return NSLocalizedString("willTheSellerInitialAndSignTheBillOfSaleIn", comment: comment)
    }

    static func odometerDisclosure(_ comment: String = "Odometer Disclosure") -> String {
        return NSLocalizedString("odometerDisclosure", comment: comment)
    }

    static func thisVehicleIsMissingInformationPleaseGoToVautoAndUpdate(_ comment: String = "This vehicle is missing information. Please go to vAuto and update this vehicle's information.") -> String {
        return NSLocalizedString("thisVehicleIsMissingInformationPleaseGoToVautoAndUpdate", comment: comment)
    }

    static func shippedDate(_ comment: String = "Shipped Date") -> String {
        return NSLocalizedString("shippedDate", comment: comment)
    }

    static func username(_ comment: String = "Username") -> String {
        return NSLocalizedString("username", comment: comment)
    }

    static func bosApproved(_ comment: String = "BOS Approved") -> String {
        return NSLocalizedString("bosApproved", comment: comment)
    }

    static func paymentRequestForm(_ comment: String = "Payment Request Form") -> String {
        return NSLocalizedString("paymentRequestForm", comment: comment)
    }

    static func allStatuses(_ comment: String = "All Statuses") -> String {
        return NSLocalizedString("allStatuses", comment: comment)
    }

    static func rejectInspection(_ comment: String = "Reject Inspection?") -> String {
        return NSLocalizedString("rejectInspection", comment: comment)
    }

    static func noResultsFound(_ comment: String = "No Results Found") -> String {
        return NSLocalizedString("noResultsFound", comment: comment)
    }

    static func completed(_ comment: String = "Completed") -> String {
        return NSLocalizedString("completed", comment: comment)
    }

    static func trim(_ comment: String = "Trim") -> String {
        return NSLocalizedString("trim", comment: comment)
    }

    static func priceNotRecognizedAsCurrency(_ comment: String = "Price Not Recognized as Currency") -> String {
        return NSLocalizedString("priceNotRecognizedAsCurrency", comment: comment)
    }

    static func no(_ comment: String = "No") -> String {
        return NSLocalizedString("no", comment: comment)
    }

    static func driverPhone(_ comment: String = "Driver Phone") -> String {
        return NSLocalizedString("driverPhone", comment: comment)
    }

    static func ok(_ comment: String = "OK") -> String {
        return NSLocalizedString("ok", comment: comment)
    }

    static func pleaseSelectAShippingFromArea(_ comment: String = "Please select a Shipping From Area") -> String {
        return NSLocalizedString("pleaseSelectAShippingFromArea", comment: comment)
    }

    static func editVehicleInformation(_ comment: String = "Edit Vehicle Information") -> String {
        return NSLocalizedString("editVehicleInformation", comment: comment)
    }

    static func rejected(_ comment: String = "Rejected") -> String {
        return NSLocalizedString("rejected", comment: comment)
    }

    static func sellerAcknowledgesTheyWillWarrantyAnyallPaintWorkDoneToThe(_ comment: String = "Seller acknowledges they will warranty any/all paint work done to the above vehicle while the vehicle is located at one of AutoSource’s dealerships and for an additional 12 months or 12,000 miles from AutoSource’s retail date of sale, whichever occurs first.") -> String {
        return NSLocalizedString("sellerAcknowledgesTheyWillWarrantyAnyallPaintWorkDoneToThe", comment: comment)
    }

    static func phoneNumberMustBeValid(_ comment: String = "Phone Number must be valid") -> String {
        return NSLocalizedString("phoneNumberMustBeValid", comment: comment)
    }

    static func clearNote(_ comment: String = "Clear Note") -> String {
        return NSLocalizedString("clearNote", comment: comment)
    }

    static func retry(_ comment: String = "Retry") -> String {
        return NSLocalizedString("retry", comment: comment)
    }

    static func clearPhoto(_ comment: String = "Clear Photo") -> String {
        return NSLocalizedString("clearPhoto", comment: comment)
    }

    static func noVehiclesSelected(_ comment: String = "No Vehicles Selected") -> String {
        return NSLocalizedString("noVehiclesSelected", comment: comment)
    }

    static func partsReplacedrepaired(_ comment: String = "Parts Replaced/Repaired") -> String {
        return NSLocalizedString("partsReplacedrepaired", comment: comment)
    }

    static func fullVinOrLast8OfVin(_ comment: String = "Full VIN or Last 8 of VIN") -> String {
        return NSLocalizedString("fullVinOrLast8OfVin", comment: comment)
    }

    static func shippedOn(_ comment: String = "Shipped On") -> String {
        return NSLocalizedString("shippedOn", comment: comment)
    }

    static func city(_ comment: String = "City") -> String {
        return NSLocalizedString("city", comment: comment)
    }

    static func supplierInformation1(_ comment: String = "Supplier Information: %1$@") -> String {
        return NSLocalizedString("supplierInformation1", comment: comment)
    }

    static func authenticating(_ comment: String = "Authenticating") -> String {
        return NSLocalizedString("authenticating", comment: comment)
    }

    static func password(_ comment: String = "Password") -> String {
        return NSLocalizedString("password", comment: comment)
    }

    static func bosAwaitingSignature(_ comment: String = "BOS Awaiting Signature") -> String {
        return NSLocalizedString("bosAwaitingSignature", comment: comment)
    }

    static func inspectorName(_ comment: String = "Inspector Name") -> String {
        return NSLocalizedString("inspectorName", comment: comment)
    }

    static func pass(_ comment: String = "Pass") -> String {
        return NSLocalizedString("pass", comment: comment)
    }

    static func firstInspection(_ comment: String = "First Inspection") -> String {
        return NSLocalizedString("firstInspection", comment: comment)
    }

    static func login(_ comment: String = "Login") -> String {
        return NSLocalizedString("login", comment: comment)
    }

    static func networkError(_ comment: String = "Network Error") -> String {
        return NSLocalizedString("networkError", comment: comment)
    }

    static func pending(_ comment: String = "Pending") -> String {
        return NSLocalizedString("pending", comment: comment)
    }

    static func selectStatus(_ comment: String = "Select Status") -> String {
        return NSLocalizedString("selectStatus", comment: comment)
    }

    static func vehicleApproved(_ comment: String = "Vehicle Approved") -> String {
        return NSLocalizedString("vehicleApproved", comment: comment)
    }

    static func reinspectionCount(_ comment: String = "Reinspection Count") -> String {
        return NSLocalizedString("reinspectionCount", comment: comment)
    }

    static func unreject(_ comment: String = "Unreject") -> String {
        return NSLocalizedString("unreject", comment: comment)
    }

    static func arrivedDate(_ comment: String = "Arrived Date") -> String {
        return NSLocalizedString("arrivedDate", comment: comment)
    }

    static func status(_ comment: String = "Status") -> String {
        return NSLocalizedString("status", comment: comment)
    }

    static func chooseOrAddADealerToSystemUnlessThisIsA(_ comment: String = "Choose or add a dealer to system unless this is a one-off sale.") -> String {
        return NSLocalizedString("chooseOrAddADealerToSystemUnlessThisIsA", comment: comment)
    }

    static func shippedFrom(_ comment: String = "Shipped From") -> String {
        return NSLocalizedString("shippedFrom", comment: comment)
    }

    static func consignment(_ comment: String = "Consignment") -> String {
        return NSLocalizedString("consignment", comment: comment)
    }

    static func supplierNumber(_ comment: String = "Supplier Number") -> String {
        return NSLocalizedString("supplierNumber", comment: comment)
    }

    static func lastKnownLocation(_ comment: String = "Last known location") -> String {
        return NSLocalizedString("lastKnownLocation", comment: comment)
    }

    static func createBillOfSalePaymentRequest(_ comment: String = "Create Bill of Sale & Payment Request") -> String {
        return NSLocalizedString("createBillOfSalePaymentRequest", comment: comment)
    }

    static func clearSearchAndFilter(_ comment: String = "Clear search and filter") -> String {
        return NSLocalizedString("clearSearchAndFilter", comment: comment)
    }

    static func vehicleFilters(_ comment: String = "Vehicle Filters") -> String {
        return NSLocalizedString("vehicleFilters", comment: comment)
    }

    static func payment(_ comment: String = "Payment") -> String {
        return NSLocalizedString("payment", comment: comment)
    }

    static func phoneNumberMustBeNoMoreThan16Digits(_ comment: String = "Phone Number must be no more than 16 digits") -> String {
        return NSLocalizedString("phoneNumberMustBeNoMoreThan16Digits", comment: comment)
    }

    static func settings(_ comment: String = "Settings") -> String {
        return NSLocalizedString("settings", comment: comment)
    }

    static func paymentMethod(_ comment: String = "Payment Method") -> String {
        return NSLocalizedString("paymentMethod", comment: comment)
    }

    static func thereWasAnErrorUpdatingTheTitleImages(_ comment: String = "There was an error updating the title images.") -> String {
        return NSLocalizedString("thereWasAnErrorUpdatingTheTitleImages", comment: comment)
    }

    static func notes(_ comment: String = "Notes") -> String {
        return NSLocalizedString("notes", comment: comment)
    }

    static func reviewBos(_ comment: String = "Review BOS") -> String {
        return NSLocalizedString("reviewBos", comment: comment)
    }

    static func bosPendingApproval(_ comment: String = "BOS Pending Approval") -> String {
        return NSLocalizedString("bosPendingApproval", comment: comment)
    }

    static func specifyOtherClassification(_ comment: String = "Specify other classification") -> String {
        return NSLocalizedString("specifyOtherClassification", comment: comment)
    }

    static func sellerSignature(_ comment: String = "Seller Signature*") -> String {
        return NSLocalizedString("sellerSignature", comment: comment)
    }

    static func thereCanOnlyBe10VehiclesPerShipment(_ comment: String = "There can only be 10 vehicles per shipment") -> String {
        return NSLocalizedString("thereCanOnlyBe10VehiclesPerShipment", comment: comment)
    }

    static func sellerType(_ comment: String = "Seller Type") -> String {
        return NSLocalizedString("sellerType", comment: comment)
    }

    static func warning(_ comment: String = "Warning") -> String {
        return NSLocalizedString("warning", comment: comment)
    }

    static func photoLibrary(_ comment: String = "Photo Library") -> String {
        return NSLocalizedString("photoLibrary", comment: comment)
    }

    static func drivetrain(_ comment: String = "Drivetrain") -> String {
        return NSLocalizedString("drivetrain", comment: comment)
    }

    static func dealerPurchaseAgreementTerms(_ comment: String = "Dealer Purchase Agreement Terms") -> String {
        return NSLocalizedString("dealerPurchaseAgreementTerms", comment: comment)
    }

    static func phone(_ comment: String = "Phone") -> String {
        return NSLocalizedString("phone", comment: comment)
    }

    static func driver(_ comment: String = "Driver") -> String {
        return NSLocalizedString("driver", comment: comment)
    }

    static func odometer(_ comment: String = "Odometer") -> String {
        return NSLocalizedString("odometer", comment: comment)
    }

    static func resendBillOfSaleForSignatures(_ comment: String = "Resend Bill of Sale for Signatures") -> String {
        return NSLocalizedString("resendBillOfSaleForSignatures", comment: comment)
    }

    static func supplierEmail(_ comment: String = "Supplier Email") -> String {
        return NSLocalizedString("supplierEmail", comment: comment)
    }

    static func bodyStyle(_ comment: String = "Body Style") -> String {
        return NSLocalizedString("bodyStyle", comment: comment)
    }

    static func driverName(_ comment: String = "Driver Name") -> String {
        return NSLocalizedString("driverName", comment: comment)
    }

    static func vehicleCheckedOutBy1231WouldLoseAnyUnsavedWorkproceedIfYou(_ comment: String = "Vehicle checked out by\n%1$@\n%2$@\n%3$@\n\n%1$@ would lose any unsaved work.\n\nProceed if you are sure you should.") -> String {
        return NSLocalizedString("vehicleCheckedOutBy1231WouldLoseAnyUnsavedWorkproceedIfYou", comment: comment)
    }

    static func search(_ comment: String = "Search") -> String {
        return NSLocalizedString("search", comment: comment)
    }

    static func createBillOfSale(_ comment: String = "Create Bill of Sale") -> String {
        return NSLocalizedString("createBillOfSale", comment: comment)
    }

    static func color(_ comment: String = "Color") -> String {
        return NSLocalizedString("color", comment: comment)
    }

    static func lastModified(_ comment: String = "Last Modified") -> String {
        return NSLocalizedString("lastModified", comment: comment)
    }

    static func zipCodeMustBeBetween5And10Digits(_ comment: String = "Zip Code must be between 5 and 10 digits") -> String {
        return NSLocalizedString("zipCodeMustBeBetween5And10Digits", comment: comment)
    }

    static func front(_ comment: String = "Front") -> String {
        return NSLocalizedString("front", comment: comment)
    }

    static func titleHistory(_ comment: String = "Title History") -> String {
        return NSLocalizedString("titleHistory", comment: comment)
    }

    static func area(_ comment: String = "Area") -> String {
        return NSLocalizedString("area", comment: comment)
    }

    static func year(_ comment: String = "Year") -> String {
        return NSLocalizedString("year", comment: comment)
    }

    static func searchForAVehicleUsingTheFullVinOrLast8(_ comment: String = "Search for a vehicle using the Full VIN or Last 8 of VIN. If the vehicle is not already in the system you will be able to enter the details manually.") -> String {
        return NSLocalizedString("searchForAVehicleUsingTheFullVinOrLast8", comment: comment)
    }

    static func billOfLadingImage1(_ comment: String = "Bill of Lading Image 1") -> String {
        return NSLocalizedString("billOfLadingImage1", comment: comment)
    }

    static func titleBackImage(_ comment: String = "Title Back Image") -> String {
        return NSLocalizedString("titleBackImage", comment: comment)
    }

    static func takePhoto(_ comment: String = "Take photo") -> String {
        return NSLocalizedString("takePhoto", comment: comment)
    }

    static func buyerSignature(_ comment: String = "Buyer Signature*") -> String {
        return NSLocalizedString("buyerSignature", comment: comment)
    }

    static func close(_ comment: String = "Close") -> String {
        return NSLocalizedString("close", comment: comment)
    }

    static func selectAnAccount(_ comment: String = "Select an Account") -> String {
        return NSLocalizedString("selectAnAccount", comment: comment)
    }

    static func vehicleCheckedOutBy123PleaseContact1BeforeContinuingOrTryAgain(_ comment: String = "Vehicle checked out by\n%1$@\n%2$@\n%3$@\n\nPlease contact %1$@ before continuing or try again in a moment.") -> String {
        return NSLocalizedString("vehicleCheckedOutBy123PleaseContact1BeforeContinuingOrTryAgain", comment: comment)
    }

    static func trimseries(_ comment: String = "Trim/Series") -> String {
        return NSLocalizedString("trimseries", comment: comment)
    }

    static func yourChangesWillBeLost(_ comment: String = "Your changes will be lost") -> String {
        return NSLocalizedString("yourChangesWillBeLost", comment: comment)
    }

    static func cylinders(_ comment: String = "Cylinders") -> String {
        return NSLocalizedString("cylinders", comment: comment)
    }

    static func shipmentNo(_ comment: String = "Shipment No - %@") -> String {
        return NSLocalizedString("shipmentNo", comment: comment)
    }

    static func createShipment(_ comment: String = "Create Shipment") -> String {
        return NSLocalizedString("createShipment", comment: comment)
    }

    static func supplyingLocation(_ comment: String = "Supplying Location") -> String {
        return NSLocalizedString("supplyingLocation", comment: comment)
    }

    static func componentIsUnacceptable(_ comment: String = "Component is unacceptable") -> String {
        return NSLocalizedString("componentIsUnacceptable", comment: comment)
    }

    static func make(_ comment: String = "Make") -> String {
        return NSLocalizedString("make", comment: comment)
    }

    static func hailDamage(_ comment: String = "Hail Damage") -> String {
        return NSLocalizedString("hailDamage", comment: comment)
    }

    static func componentHasBeenAcceptablyRepaired(_ comment: String = "Component has been acceptably repaired") -> String {
        return NSLocalizedString("componentHasBeenAcceptablyRepaired", comment: comment)
    }

    static func fixed(_ comment: String = "Fixed") -> String {
        return NSLocalizedString("fixed", comment: comment)
    }

    static func sendToSupplier(_ comment: String = "Send to Supplier") -> String {
        return NSLocalizedString("sendToSupplier", comment: comment)
    }

    static func actualMileage(_ comment: String = "Actual Mileage") -> String {
        return NSLocalizedString("actualMileage", comment: comment)
    }

    static func shipments(_ comment: String = "Shipments") -> String {
        return NSLocalizedString("shipments", comment: comment)
    }

    static func noInspectionsMatchedTheSpecifiedCriteria(_ comment: String = "No inspections matched the specified criteria") -> String {
        return NSLocalizedString("noInspectionsMatchedTheSpecifiedCriteria", comment: comment)
    }

    static func address(_ comment: String = "Address") -> String {
        return NSLocalizedString("address", comment: comment)
    }

    static func sellerAcknowledgesTheyWillBeResponsibleForAllShippingCostsIncurred(_ comment: String = "Seller acknowledges they will be responsible for all shipping costs incurred if the vehicle is to be sent back for any reason, and will pay AutoSource before they pick up the vehicle from AutoSource Office.") -> String {
        return NSLocalizedString("sellerAcknowledgesTheyWillBeResponsibleForAllShippingCostsIncurred", comment: comment)
    }

    static func installTheAsnSuppliersToolInOrderToAddSupplierInformation(_ comment: String = "Install the ASN Suppliers tool in order to add Supplier information.") -> String {
        return NSLocalizedString("installTheAsnSuppliersToolInOrderToAddSupplierInformation", comment: comment)
    }

    static func submitBospmt(_ comment: String = "Submit BOS/PMT") -> String {
        return NSLocalizedString("submitBospmt", comment: comment)
    }

    static func collision(_ comment: String = "Collision") -> String {
        return NSLocalizedString("collision", comment: comment)
    }

    static func inspectionPassed(_ comment: String = "Inspection Passed") -> String {
        return NSLocalizedString("inspectionPassed", comment: comment)
    }

    static func bankAccount(_ comment: String = "Bank Account") -> String {
        return NSLocalizedString("bankAccount", comment: comment)
    }

    static func toReinspectSupplier(_ comment: String = "To Reinspect @ Supplier") -> String {
        return NSLocalizedString("toReinspectSupplier", comment: comment)
    }

    static func retakeImages(_ comment: String = "Retake Images") -> String {
        return NSLocalizedString("retakeImages", comment: comment)
    }

    static func selectVehicle(_ comment: String = "Select Vehicle") -> String {
        return NSLocalizedString("selectVehicle", comment: comment)
    }

    static func titleClassification(_ comment: String = "Title Classification") -> String {
        return NSLocalizedString("titleClassification", comment: comment)
    }

    static func sellerWillNeedToBeAvailableViaPhonePhoneNumberAbove(_ comment: String = "Seller will need to be available via phone (phone number above) during AutoSource business hours Mon-Sat 10-7pm for any/all retail customer negotiations. If Seller does not respond via text or call, AutoSource can lower their cost up to $500 without their permission to consummate any deal.") -> String {
        return NSLocalizedString("sellerWillNeedToBeAvailableViaPhonePhoneNumberAbove", comment: comment)
    }

    static func addressLine2(_ comment: String = "Address Line 2") -> String {
        return NSLocalizedString("addressLine2", comment: comment)
    }

    static func noInspector(_ comment: String = "No Inspector") -> String {
        return NSLocalizedString("noInspector", comment: comment)
    }

    static func logout(_ comment: String = "Logout") -> String {
        return NSLocalizedString("logout", comment: comment)
    }

    static func denotesPreferredAccount(_ comment: String = "* denotes preferred account") -> String {
        return NSLocalizedString("denotesPreferredAccount", comment: comment)
    }

    static func markInTransit(_ comment: String = "Mark in Transit") -> String {
        return NSLocalizedString("markInTransit", comment: comment)
    }

    static func loading(_ comment: String = "Loading...") -> String {
        return NSLocalizedString("loading", comment: comment)
    }

    static func rejectionReason(_ comment: String = "Rejection Reason") -> String {
        return NSLocalizedString("rejectionReason", comment: comment)
    }

    static func fullPurchase(_ comment: String = "Full Purchase") -> String {
        return NSLocalizedString("fullPurchase", comment: comment)
    }

    static func searchEverywhere(_ comment: String = "Search Everywhere") -> String {
        return NSLocalizedString("searchEverywhere", comment: comment)
    }

    static func checkOut(_ comment: String = "Check Out") -> String {
        return NSLocalizedString("checkOut", comment: comment)
    }

    static func preferred(_ comment: String = "Preferred") -> String {
        return NSLocalizedString("preferred", comment: comment)
    }

    static func dealer(_ comment: String = "Dealer") -> String {
        return NSLocalizedString("dealer", comment: comment)
    }

    static func paymentRequested(_ comment: String = "Payment Requested") -> String {
        return NSLocalizedString("paymentRequested", comment: comment)
    }

    static func yes(_ comment: String = "Yes") -> String {
        return NSLocalizedString("yes", comment: comment)
    }


}
